name: call-on-pull-request

on:
    pull_request:
        types: [opened, reopened]

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                npm install
                npm run build
                npm run compile
            - name: Commit files
              run: |
                  git config --local user.email "zezongo@gmail.com"
                  git config --local user.name "guilhemheinrich"
                  git commit -a -m "[Automated] Generate bundled code"
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ github.ref }}